---
kind: pipeline
name: integration
steps:
  - name: molecule test
    image: python:3.8-buster
    environment:
      MOLECULE_NO_LOG: false
      HCLOUD_TOKEN:
        from_secret: HCLOUD_TOKEN
    commands:
      - pip install -e .
      - export INSTANCE_UUID=$(echo $$RANDOM)
      - cd integration && molecule test
