---
kind: pipeline
name: linters
steps:
  - name: tox -e linters
    image: python:3.9-buster
    commands:
      - pip install tox
      - tox -e linters

---
kind: pipeline
name: packaging
steps:
  - name: tox -e packaging
    image: python:3.9-buster
    commands:
      - pip install tox
      - tox -e packaging
depends_on:
  - linters

---
kind: pipeline
name: py36
steps:
  - name: tox -e py36
    image: python:3.6-buster
    commands:
      - pip install tox
      - tox -e py36
depends_on:
  - linters

---
kind: pipeline
name: py37
steps:
  - name: tox -e py37
    image: python:3.7-buster
    commands:
      - pip install tox
      - tox -e py37
depends_on:
  - linters

---
kind: pipeline
name: py38
steps:
  - name: tox -e py38
    image: python:3.8-buster
    commands:
      - pip install tox
      - tox -e py38
depends_on:
  - linters

---
kind: pipeline
name: devel
steps:
  - name: tox -e devel
    image: python:3.9-buster
    failure: ignore
    commands:
      - pip install tox
      - tox -e devel
depends_on:
  - linters

---
kind: pipeline
name: integration
steps:
  - name: molecule test
    image: python:3.9-buster
    environment:
      MOLECULE_NO_LOG: false
      HCLOUD_TOKEN:
        from_secret: HCLOUD_TOKEN
    commands:
      - pip install -e .
      - pip install "ansible>=2.10, <2.11"
      - export INSTANCE_UUID=$(openssl rand -hex 5)
      - cd integration && molecule test
depends_on:
  - linters
  - packaging
  - py36
  - py37
  - py38
