---
matrix:
  include:
    - IMAGE: 3.8-buster
      TOXENV: linters

    - IMAGE: 3.8-buster
      TOXENV: packaging

    - IMAGE: 3.8-buster
      TOXENV: py38

pipeline:
  build:
    image: python:${IMAGE}
    commands:
      - pip install tox==3.14.6
      - tox -e ${TOXENV}
  integration:
    image: python:3.8-buster
    commands:
      - pip install -e .
      - cd integration-test-role && molecule test
