---
kind: pipeline
name: integration
steps:
  - name: molecule test
    image: python:3.8-buster
    environment:
      HCLOUD_TOKEN:
        from_secret: HCLOUD_TOKEN
      MOLECULE_DEBUG: true
    commands:
      - pip install -e .
      - export INSTANCE_UUID=$(echo $$RANDOM)
      - cd integration-test-role && molecule test
