---
kind: pipeline
name: integration
steps:
  - name: molecule test
    image: python:3.8-buster
    environment:
      HCLOUD_TOKEN:
        from_secret: HCLOUD_TOKEN
    commands:
      - pip install -e .
      - cd integration-test-role && molecule test
