[tool.isort]
profile = "black"
combine_as_imports = true
add_imports = ["from __future__ import annotations"]

[tool.coverage.run]
source = ["molecule_hetznercloud"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
