---
collections:
  - name: community.crypto
    version: 3.0.5

  - name: hetzner.hcloud
    version: 5.4.0

  - name: ansible.netcommon
    version: 8.2.0

  - name: ansible.utils
    version: 6.0.0
