---
collections:
  - name: community.crypto
    version: 3.0.3

  - name: hetzner.hcloud
    version: 5.3.1

  - name: ansible.netcommon
    version: 8.1.0

  - name: ansible.utils
    version: 6.0.0
