---
collections:
  - name: community.crypto
    version: 3.2.0

  - name: hetzner.hcloud
    version: 6.8.0

  - name: ansible.netcommon
    version: 8.5.0

  - name: ansible.utils
    version: 6.0.2
