---
collections:
  - name: community.crypto
    version: 3.0.1

  - name: hetzner.hcloud
    version: 5.1.0

  - name: ansible.netcommon
    version: 8.0.1

  - name: ansible.utils
    version: 6.0.0
