---
collections:
  - name: community.crypto
    version: 3.3.0

  - name: hetzner.hcloud
    version: 6.10.0

  - name: ansible.netcommon
    version: 8.6.0

  - name: ansible.utils
    version: 6.0.3
