---
collections:
  - name: community.crypto
    version: 3.4.0

  - name: hetzner.hcloud
    version: 6.12.0

  - name: ansible.netcommon
    version: 8.6.2

  - name: ansible.utils
    version: 6.1.0
