---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: "molecule-hetznercloud-${INSTANCE_UUID}"
    server_type: cx11
    image: debian-10
    volumes:
      name: "molecule-hetznercloud-volume-${INSTANCE_UUID}"
      size: 11
      create: true
provisioner:
  name: ansible
verifier:
  name: ansible
