name: Releaser-pleaser

on:
  push:
    branches: [main]
  pull_request_target:
    types:
      - edited
      - labeled
      - unlabeled

jobs:
  releaser-pleaser:
    # Do not run on forks.
    if: github.repository == 'ansible-community/molecule-hetznercloud'

    runs-on: ubuntu-latest
    steps:
      - name: releaser-pleaser
        uses: apricote/releaser-pleaser@v0.5.1
        with:
          token: ${{ secrets.HCLOUD_BOT_TOKEN }}
          extra-files: |
            molecule_hetznercloud/_version.py
            setup.py
